// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("023a16f1-6f58-4611-93e0-3b8a46e647a4")]
    public class DireDungeonsEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create DireDungeons Kernel", false, 0)]
        public static void AddKernel() {
            Invert.uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<DireDungeons.DireDungeonsLoader>();
        }
    }
}
