// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("64398f93-57bd-4423-95b4-8ec581d615fb")]
    public partial class Driver : uFrame.ECS.EcsComponent {
        
        private Subject<String> _FirstSceneObservable;
        
        [UnityEngine.SerializeField()]
        private String _FirstScene;
        
        public int ComponentID {
            get {
                return 1;
            }
        }
        
        public IObservable<String> FirstSceneObservable {
            get {
                if (_FirstSceneObservable == null) {
                    _FirstSceneObservable = new Subject<String>();
                }
                return _FirstSceneObservable;
            }
        }
        
        public String FirstScene {
            get {
                return _FirstScene;
            }
            set {
                _FirstScene = value;
                if (_FirstSceneObservable != null) {
                    _FirstSceneObservable.OnNext(value);
                }
            }
        }
    }
}
