// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using DireDungeons;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("8cca1ecf-cbc1-427c-a52c-f2cd14390bb4")]
    public partial class PhotonComponent : uFrame.ECS.EcsComponent {
        
        private Subject<PhotonView> _PhotonViewObservable;
        
        [UnityEngine.SerializeField()]
        private PhotonView _PhotonView;
        
        public int ComponentID {
            get {
                return 3;
            }
        }
        
        public IObservable<PhotonView> PhotonViewObservable {
            get {
                if (_PhotonViewObservable == null) {
                    _PhotonViewObservable = new Subject<PhotonView>();
                }
                return _PhotonViewObservable;
            }
        }
        
        public PhotonView PhotonView {
            get {
                return _PhotonView;
            }
            set {
                _PhotonView = value;
                if (_PhotonViewObservable != null) {
                    _PhotonViewObservable.OnNext(value);
                }
            }
        }
    }
}
