// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("182d48a4-54ff-4f00-9187-a68aed7f7161")]
    public partial class Room : uFrame.ECS.EcsComponent {
        
        private Subject<String> _RoomIdObservable;
        
        [UnityEngine.SerializeField()]
        private String _RoomId;
        
        public int ComponentID {
            get {
                return 3;
            }
        }
        
        public IObservable<String> RoomIdObservable {
            get {
                if (_RoomIdObservable == null) {
                    _RoomIdObservable = new Subject<String>();
                }
                return _RoomIdObservable;
            }
        }
        
        public String RoomId {
            get {
                return _RoomId;
            }
            set {
                _RoomId = value;
                if (_RoomIdObservable != null) {
                    _RoomIdObservable.OnNext(value);
                }
            }
        }
    }
}
