// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("eacacb92-d5f8-4d98-a588-23ec36f27b60")]
    public partial class UpdateConnected : uFrame.ECS.EcsComponent {
        
        private Subject<GameObject> _obj_txtConnectedObservable;
        
        [UnityEngine.SerializeField()]
        private GameObject _obj_txtConnected;
        
        public int ComponentID {
            get {
                return 6;
            }
        }
        
        public IObservable<GameObject> obj_txtConnectedObservable {
            get {
                if (_obj_txtConnectedObservable == null) {
                    _obj_txtConnectedObservable = new Subject<GameObject>();
                }
                return _obj_txtConnectedObservable;
            }
        }
        
        public GameObject obj_txtConnected {
            get {
                return _obj_txtConnected;
            }
            set {
                _obj_txtConnected = value;
                if (_obj_txtConnectedObservable != null) {
                    _obj_txtConnectedObservable.OnNext(value);
                }
            }
        }
    }
}
