// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UnityEngine;
    
    
    [uFrame.Attributes.ActionTitle("TryJoinRoom")]
    public partial class TryJoinRoom : uFrame.Actions.UFAction {
        
        [uFrame.Attributes.In("RoomId")]
        public String RoomId;
        
        [uFrame.Attributes.Out("Yes")]
        public System.Action Yes;
        
        [uFrame.Attributes.Out("No")]
        public System.Action No;
    }
}
