// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UnityEngine;
    
    
    [uFrame.Attributes.ActionTitle("UnloadScene")]
    public partial class UnloadScene : uFrame.Actions.UFAction {
        
        [uFrame.Attributes.In("OldScene")]
        public String OldScene;
    }
}
