// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class KernelUnloadSceneEventHandler {
        
        private DireDungeons.UnloadSceneEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode6_OldScene = default( System.String );
        
        private DireDungeons.UnloadScene ActionNode6 = new DireDungeons.UnloadScene();
        
        public DireDungeons.UnloadSceneEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode6_OldScene = Event.SceneName;
            // ActionNode
            while (this.DebugInfo("37703d78-4f9a-4115-8866-c20950a745b8","52079bb7-b0ba-4b76-a260-e46ff3664f0b", this) == 1) yield return null;
            // Visit DireDungeons.UnloadScene
            ActionNode6.OldScene = ActionNode6_OldScene;
            ActionNode6.System = System;
            ActionNode6.Execute();
            yield break;
        }
    }
}
