// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class KernelLoadSceneEventHandler {
        
        private DireDungeons.LoadSceneEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode4_NewScene = default( System.String );
        
        private DireDungeons.LoadScene ActionNode4 = new DireDungeons.LoadScene();
        
        public DireDungeons.LoadSceneEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode4_NewScene = Event.SceneName;
            // ActionNode
            while (this.DebugInfo("b42d3ce5-547d-4f35-a12d-d7e7d5f9bafd","37703d78-4f9a-4115-8866-c20950a745b8", this) == 1) yield return null;
            // Visit DireDungeons.LoadScene
            ActionNode4.NewScene = ActionNode4_NewScene;
            ActionNode4.System = System;
            ActionNode4.Execute();
            yield break;
        }
    }
}
