// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class KernelGameReadyHandler {
        
        public Driver Group;
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private DireDungeons.LoadSceneEvent PublishEventNode2_Result = default( DireDungeons.LoadSceneEvent );
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("","b42d3ce5-547d-4f35-a12d-d7e7d5f9bafd", this) == 1) yield return null;
            var PublishEventNode2_Event = new LoadSceneEvent();
            PublishEventNode2_Event.SceneName = Group.FirstScene;
            System.Publish(PublishEventNode2_Event);
            PublishEventNode2_Event = PublishEventNode2_Result;
            yield break;
        }
    }
}
