// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class LobbySystemUpdateHandler {
        
        public UpdateConnected Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode41_Obj_TxtConnecting = default( UnityEngine.GameObject );
        
        private DireDungeons.UpdateConnectionStatus ActionNode41 = new DireDungeons.UpdateConnectionStatus();
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode41_Obj_TxtConnecting = Group.obj_txtConnected;
            // ActionNode
            while (this.DebugInfo("3441e635-5712-4096-aaa7-43b4ed1c16ae","a580f04c-44e3-42c8-93b7-396f7ad3b9f6", this) == 1) yield return null;
            // Visit DireDungeons.UpdateConnectionStatus
            ActionNode41.Obj_TxtConnecting = ActionNode41_Obj_TxtConnecting;
            ActionNode41.System = System;
            ActionNode41.Execute();
            yield break;
        }
    }
}
