// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class LobbySystemPointerClickHandler {
        
        public LobbyButton Source;
        
        private uFrame.ECS.PointerClickDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode3_RoomId = default( System.String );
        
        private int ActionNode3_MaxPlayers = default( System.Int32 );
        
        private DireDungeons.TryJoinRoom ActionNode3 = new DireDungeons.TryJoinRoom();
        
        public uFrame.ECS.PointerClickDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode3_RoomId = Source.RoomId;
            ActionNode3_MaxPlayers = Source.MaxPlayers;
            // ActionNode
            while (this.DebugInfo("37703d78-4f9a-4115-8866-c20950a745b8","3360ff9c-8e01-4268-a11d-0c0f9e72462d", this) == 1) yield return null;
            // Visit DireDungeons.TryJoinRoom
            ActionNode3.RoomId = ActionNode3_RoomId;
            ActionNode3.MaxPlayers = ActionNode3_MaxPlayers;
            ActionNode3.System = System;
            ActionNode3.Execute();
            yield break;
        }
    }
}
