// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class LobbySystemOnConnectedToMasterHandler {
        
        public LobbyMenu Source;
        
        private uFrame.ECS.OnConnectedToMasterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode32_Obj_Connecting = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode32_Obj_Rooms = default( UnityEngine.GameObject );
        
        private DireDungeons.ShowLobby ActionNode32 = new DireDungeons.ShowLobby();
        
        private UnityEngine.MonoBehaviour ActionNode49_behaviour = default( UnityEngine.MonoBehaviour );
        
        public uFrame.ECS.OnConnectedToMasterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode32_Obj_Connecting = Source.obj_Connecting;
            ActionNode32_Obj_Rooms = Source.obj_Rooms;
            // ActionNode
            while (this.DebugInfo("3360ff9c-8e01-4268-a11d-0c0f9e72462d","6e6ab7ff-5ebc-47b4-86a9-26ce7c4ef0af", this) == 1) yield return null;
            // Visit DireDungeons.ShowLobby
            ActionNode32.Obj_Connecting = ActionNode32_Obj_Connecting;
            ActionNode32.Obj_Rooms = ActionNode32_Obj_Rooms;
            ActionNode32.System = System;
            ActionNode32.Execute();
            // ActionNode
            while (this.DebugInfo("6e6ab7ff-5ebc-47b4-86a9-26ce7c4ef0af","3441e635-5712-4096-aaa7-43b4ed1c16ae", this) == 1) yield return null;
            // Visit uFrame.Actions.DestroyLibrary.DestroyComponent
            uFrame.Actions.DestroyLibrary.DestroyComponent(ActionNode49_behaviour);
            yield break;
        }
    }
}
