// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class PhotonSystemOnJoinedRoomHandler {
        
        public LobbyButton Source;
        
        private uFrame.ECS.OnJoinedRoomDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string StringNode15 = "Lobby";
        
        private DireDungeons.UnloadSceneEvent PublishEventNode17_Result = default( DireDungeons.UnloadSceneEvent );
        
        private DireDungeons.LoadSceneEvent PublishEventNode16_Result = default( DireDungeons.LoadSceneEvent );
        
        public uFrame.ECS.OnJoinedRoomDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("834a4a73-c79a-4c81-bd10-1cb6b733d6c2","42358967-98df-48f7-8ca4-8c75f51cca35", this) == 1) yield return null;
            var PublishEventNode17_Event = new UnloadSceneEvent();
            PublishEventNode17_Event.SceneName = StringNode15;
            System.Publish(PublishEventNode17_Event);
            PublishEventNode17_Event = PublishEventNode17_Result;
            // PublishEventNode
            while (this.DebugInfo("42358967-98df-48f7-8ca4-8c75f51cca35","e03f68f8-7483-40e8-a4ed-d2243c3a140d", this) == 1) yield return null;
            var PublishEventNode16_Event = new LoadSceneEvent();
            PublishEventNode16_Event.SceneName = Source.RoomId;
            System.Publish(PublishEventNode16_Event);
            PublishEventNode16_Event = PublishEventNode16_Result;
            yield break;
        }
    }
}
