// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class PhotonSystemLevelWasLoadedHandler {
        
        public Room Group;
        
        private uFrame.Kernel.LevelWasLoadedEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode27_a = default( System.Object );
        
        private object ActionNode27_b = default( System.Object );
        
        private bool ActionNode27_Result = default( System.Boolean );
        
        private string ActionNode25_SceneId = default( System.String );
        
        private DireDungeons.EnterRoom ActionNode25 = new DireDungeons.EnterRoom();
        
        public uFrame.Kernel.LevelWasLoadedEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode27_a = Event.SceneId;
            ActionNode27_b = Group.RoomId;
            // ActionNode
            while (this.DebugInfo("1b6e480f-e9a4-4548-a35a-e44cae0f45d9","633b18b4-c679-4eb2-b2d7-fa8e750da7a8", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.AreEqual
            ActionNode27_Result = uFrame.Actions.Comparisons.AreEqual(ActionNode27_a, ActionNode27_b, ()=> { System.StartCoroutine(ActionNode27_yes()); }, ()=> { System.StartCoroutine(ActionNode27_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode27_yes() {
            ActionNode25_SceneId = Event.SceneId;
            // ActionNode
            while (this.DebugInfo("633b18b4-c679-4eb2-b2d7-fa8e750da7a8","a96266ec-6324-47a3-948b-c690e9aaca89", this) == 1) yield return null;
            // Visit DireDungeons.EnterRoom
            ActionNode25.SceneId = ActionNode25_SceneId;
            ActionNode25.System = System;
            ActionNode25.Execute();
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode27_no() {
            yield break;
        }
    }
}
