// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DireDungeons {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class RoomSystemOnJoinedRoomHandler {
        
        public LobbyButton Source;
        
        private uFrame.ECS.OnJoinedRoomDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string StringNode15 = "Lobby";
        
        private DireDungeons.UnloadSceneEvent PublishEventNode17_Result = default( DireDungeons.UnloadSceneEvent );
        
        private DireDungeons.LoadSceneEvent PublishEventNode16_Result = default( DireDungeons.LoadSceneEvent );
        
        private string ActionNode12_RoomId = default( System.String );
        
        private DireDungeons.EnterRoom ActionNode12 = new DireDungeons.EnterRoom();
        
        public uFrame.ECS.OnJoinedRoomDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("71e376ca-c9af-4004-b485-e398d05f7f78","4f101bab-d06a-48da-ab88-077be88c892c", this) == 1) yield return null;
            var PublishEventNode17_Event = new UnloadSceneEvent();
            PublishEventNode17_Event.SceneName = StringNode15;
            System.Publish(PublishEventNode17_Event);
            PublishEventNode17_Event = PublishEventNode17_Result;
            // PublishEventNode
            while (this.DebugInfo("4f101bab-d06a-48da-ab88-077be88c892c","d81e5933-b1a3-4d83-abf7-eefd44b20ba9", this) == 1) yield return null;
            var PublishEventNode16_Event = new LoadSceneEvent();
            PublishEventNode16_Event.SceneName = Source.RoomId;
            System.Publish(PublishEventNode16_Event);
            PublishEventNode16_Event = PublishEventNode16_Result;
            ActionNode12_RoomId = Source.RoomId;
            // ActionNode
            while (this.DebugInfo("d81e5933-b1a3-4d83-abf7-eefd44b20ba9","619ec665-d662-4d22-96d7-96acba550eb7", this) == 1) yield return null;
            // Visit DireDungeons.EnterRoom
            ActionNode12.RoomId = ActionNode12_RoomId;
            ActionNode12.System = System;
            ActionNode12.Execute();
            yield break;
        }
    }
}
